processors:
  - dll: D:\Work\ProcessorsAgent\ElasticProcessor\bin\Debug\net6.0\ElasticProcessor.dll
    config: D:\Work\ProcessorsAgent\SuperAgent\config\processor-elastic.yaml
    name: Elasticsearch writer1
connectors:
  - destination: Elasticsearch writer1
    input: kafka
    inputConfig: D:\Work\ProcessorsAgent\SuperAgent\config\input-kafka.yaml
    output: kafka
    outputConfig: D:\Work\ProcessorsAgent\SuperAgent\config\output-kafka.yaml