//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Libs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ElasticClientResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ElasticClientResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Localization.Libs.ElasticClientResources", typeof(ElasticClientResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElasticSearch server {0}:{1} is not available {2} seconds.
        /// </summary>
        public static string ElasticSearchNotAvailable {
            get {
                return ResourceManager.GetString("ElasticSearchNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ElasticSearch server is not healthy. Output: \n {0}.
        /// </summary>
        public static string ElasticSearchNotHealthy {
            get {
                return ResourceManager.GetString("ElasticSearchNotHealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to elasticSearch server ({0}) canceled because of too big delay.
        /// </summary>
        public static string TooBigDelayFromElastic {
            get {
                return ResourceManager.GetString("TooBigDelayFromElastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown authentication type.
        /// </summary>
        public static string UnknownAuthenticationType {
            get {
                return ResourceManager.GetString("UnknownAuthenticationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wrong type of file. need to be .yaml.
        /// </summary>
        public static string WrongTypeOfFileNeedToBeYaml {
            get {
                return ResourceManager.GetString("WrongTypeOfFileNeedToBeYaml", resourceCulture);
            }
        }
    }
}
